on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  sqlite:
    name: "SQLite & Python 3.7"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v2
      - name: "Set up Python 3.7"
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: "Install dependencies"
        run: pip install -e .[dev,csp]
      - name: "Lint project"
        run: flake8 && isort -q -c --df .
      - name: "Run tests"
        run: py.test
        if: success()
        env:
          DB: sqlite
      - name: "Check coverage"
        uses: AndreMiras/coveralls-python-action@v20201129
        if: success()
        with:
          parallel: true
          flag-name: sqlite
          github-token: ${{secrets.COVERALLS_TOKEN}}
      - name: "Send status to Discord"
        uses: MangAdventure/discord-webhook@v0.1
        if: always()
        with:
          lang-name: Python
          lang-version: 3.7
          webhook-url: ${{secrets.DISCORD_WEBHOOK}}

  mysql:
    name: "MySQL & Python 3.8"
    runs-on: ubuntu-latest
    services:
      postgres:
        image: mariadb:10
        ports: [3306]
        env:
          MYSQL_DATABASE: mangadv
          MYSQL_ROOT_PASSWORD: ${{secrets.DB_PASSWORD}}
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v2
      - name: "Set up Python 3.8"
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: "Install dependencies"
        run: pip install -e .[dev,mysql]
      - name: "Lint project"
        run: flake8 && isort -q -c --df .
      - name: "Run tests"
        run: py.test
        if: success()
        env:
          DB: mysql
      - name: "Check coverage"
        uses: AndreMiras/coveralls-python-action@v20201129
        if: success()
        with:
          parallel: true
          flag-name: mysql
          github-token: ${{secrets.COVERALLS_TOKEN}}
      - name: "Send status to Discord"
        uses: MangAdventure/discord-webhook@v0.1
        if: always()
        with:
          lang-name: Python
          lang-version: 3.8
          webhook-url: ${{secrets.DISCORD_WEBHOOK}}

  postgresql:
    name: "PostgreSQL & Python 3.9"
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        ports: [5432]
        env:
          POSTGRES_DB: mangadv
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: ${{secrets.DB_PASSWORD}}
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v2
      - name: "Set up Python 3.9"
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: "Install dependencies"
        run: pip install -e .[dev,pgsql]
      - name: "Lint project"
        run: flake8 && isort -q -c --df .
      - name: "Run tests"
        run: py.test
        if: success()
        env:
          DB: postgresql
      - name: "Check coverage"
        uses: AndreMiras/coveralls-python-action@v20201129
        if: success()
        with:
          parallel: true
          flag-name: postgresql
          github-token: ${{secrets.COVERALLS_TOKEN}}
      - name: "Send status to Discord"
        uses: MangAdventure/discord-webhook@v0.1
        if: always()
        with:
          lang-name: Python
          lang-version: 3.9
          webhook-url: ${{secrets.DISCORD_WEBHOOK}}

  coveralls:
    needs: [sqlite, mysql, postgresql]
    runs-on: ubuntu-latest
    steps:
      - name: "Upload coverage"
        uses: AndreMiras/coveralls-python-action@v20201129
        with:
          parallel-finished: true
          github-token: ${{secrets.COVERALLS_TOKEN}}
